import { Inter, Libre_Baskerville, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "../app/components/header";
import  Footer  from "../app/components/footer";
const libre = Libre_Baskerville({ weight: ['400','700'], subsets: ["latin"] });
const inter = Inter({ weight: ['400','700'], subsets: ["latin"] });
const quicksand = Quicksand ({ weight: ['400','700'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="h-screen">
        <Header className={quicksand.className}></Header>
          <section className={libre.className}>
            {children}
          </section>
        <Footer className={quicksand.className}></Footer>
      </body>
      
    </html>
  );
}
